
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'Download artefacts'
  name: 'hashicorp/terraform:0.14.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      wget -P gcp/cloud-functions https://github.com/jorgeacf/gcp-examples/releases/download/latest/cloud-functions-java-release.zip
      ls -al gcp/cloud-functions

- id: 'tf fmt'
  name: 'hashicorp/terraform:0.14.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform fmt -recursive

- id: 'tf init'
  name: 'hashicorp/terraform:0.14.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init

- id: 'tf validate'
  name: 'hashicorp/terraform:0.14.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform validate -no-color

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform plan -no-color

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform apply -auto-approve -no-color