name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_SA }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.14.10
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    #defaults:
    #  run:
    #    shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Format'
      run: terraform --version

    - name: 'Download artefacts'
      run: wget -o cloud-functions-java-release.zip https://github.com/jorgeacf/gcp-examples/releases/download/latest/cloud-functions-java-release.zip

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive

    - name: Terraform Init
      id: init
      run: terraform init -no-color

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color

    - name: Check files
      id: check-files
      run: ls -al
